Summary:	The most beautiful way to optimize your applications
Summary(pl):	Naj³adniejszy sposób optymalizowania aplikacji
Name:		kcachegrind
Version:	0.4.4
Release:	1
License:	GPL
Group:		Development/Tools
Source0:	http://kcachegrind.sourceforge.net/%{name}-%{version}.tar.gz
# Source0-md5:	874e78af54a661495cbb29922133ab0f
URL:		http://kcachegrind.sourceforge.net/cgi-bin/show.cgi
BuildRequires:	fam-devel
BuildRequires:	kdelibs-devel
BuildRequires:	libart_lgpl-devel
BuildRequires:	libjpeg-devel
BuildRequires:	libpng-devel
Requires:	binutils
Requires:	graphviz
Requires:	valgrind-calltree
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%description
KCachegrind is the most beautiful way to optimize your applications -
a visualisation tool for the profiling data generated by Cachegrind
and Calltree.

%description -l pl
KCachegrind to naj³adniejszy sposób optymalizowania aplikacji -
narzêdzie wizualizacyjne do danych profiluj±cych wygenerowanych przez
Cachegrinda i Calltree.

%prep
%setup -q

%build
%configure
echo "all:" >doc/en/Makefile	# disable docbook documentation building
echo >>doc/en/Makefile
echo "install:" >>doc/en/Makefile
%{__make}

%install
rm -rf $RPM_BUILD_ROOT

%{__make} install \
	DESTDIR=$RPM_BUILD_ROOT \
	kde_appsdir=%{_applnkdir}

%find_lang %{name}

%clean
rm -rf $RPM_BUILD_ROOT

%files -f %{name}.lang
%defattr(644,root,root,755)
%doc AUTHORS ChangeLog README README.KDE TODO
%attr(755,root,root) %{_bindir}/*
%{_datadir}/apps/%{name}
%{_datadir}/mimelnk/application/*
%{_iconsdir}/*/*/*/*.png
%{_applnkdir}/Development/*.desktop
